spring:
  datasource:
    username: root
    password: as661778
    url: jdbc:mysql://localhost:3306/softwaretest
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    protocol: smtp #发送邮件协议
    host: smtp.126.com
    username: nzh1094554173@126.com
    password: MWCDEEUTVNSBPTWX
    port:
file:
  path: C:\\uploadTest
  webPath: C:/uploadTest