spring:
#  mvc:
#    servlet:
#      path: /api
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB  #单个文件最大大小
      max-request-size: 6000MB #上传数据总大小

mybatis-plus:
  mapper-locations: mapper/**/*.xml

server:
  port: 9099

jwt:
  key: tongjinzh
  time: 30

knife4j:
  enable: true
  title: 软件工程课设文档
  description: 接口咨询qq--1094554173,对抗练习收工！！大家辛苦啦
  version: 4.0



