spring:
  banner:
    location: banner.txt
  mvc:
    servlet:
      path: /api
  profiles:
    active: prod

  servlet:
    multipart:
      enabled: true
      max-file-size: 2000MB  #单个文件最大大小
      max-request-size: 6000MB #上传数据总大小

#mybatis-plus:
  #mapper-locations: mapper/**/*.xml

server:
  port: 9090

jwt:
  key: tongjinzh
  time: 30

knife4j:
  enable: true


